name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: |
        cd tools/cpp_code_analyzer/
        cargo build --verbose
    - name: Run tests
      run: |
        cd tools/cpp_code_analyzer/
        cargo test --verbose
